// Fictional, simplified service-desk scenarios for the Rush Hour game.
// The engine shuffles action positions; patches leave the original request open.
export const TICKETS = [
  {
    id: 'dns-museum',
    category: 'NETWORK',
    title: 'The DNS museum',
    quote: 'The portal moved. My laptop is preserving the historic address.',
    clue: 'Only this laptop resolves the portal to its old IP. Its local DNS cache still holds that address.',
    user: 'Nina · Operations',
    icon: '🌐',
    actions: [
      { label: 'Refresh the local DNS cache', kind: 'fix', outcome: 'Current address found. Museum closed.' },
      { label: 'Lend an approved spare laptop', kind: 'patch', outcome: 'Spare works. Please fix my own laptop.' },
      { label: 'Clear the portal cookies', kind: 'wrong', outcome: 'Fewer cookies. Same old address.' },
    ],
  },
  {
    id: 'monitor-voices',
    category: 'AUDIO',
    title: 'Meeting by monitor',
    quote: 'Everyone sounds trapped inside my screen. I need my headset.',
    clue: 'Audio output is HDMI Monitor. The connected headset passes its sound test.',
    user: 'Theo · Sales',
    icon: '🎧',
    actions: [
      { label: 'Select the headset output', kind: 'fix', outcome: 'Voices return to the correct ears.' },
      { label: 'Use speakers in the empty room', kind: 'patch', outcome: 'Audible here. I still need my headset.' },
      { label: 'Increase microphone gain', kind: 'wrong', outcome: 'Your voice gets louder. Theirs does not.' },
    ],
  },
  {
    id: 'camera-shutter',
    category: 'VIDEO',
    title: 'Webcam witness protection',
    quote: 'My webcam has chosen a mysterious silhouette for the demo.',
    clue: 'The webcam is detected and enabled. Its physical privacy shutter is closed.',
    user: 'Priya · Design',
    icon: '📷',
    actions: [
      { label: 'Open the privacy shutter', kind: 'fix', outcome: 'Mystery guest identified.' },
      { label: 'Join with audio only for now', kind: 'patch', outcome: 'Present, but the demo still needs video.' },
      { label: 'Change the virtual background', kind: 'wrong', outcome: 'New scenery. Same closed shutter.' },
    ],
  },
  {
    id: 'wrong-monitor-input',
    category: 'DISPLAY',
    title: 'Wrong channel, no remote',
    quote: 'The second screen is conducting a silent protest.',
    clue: 'The cable is connected to HDMI 2. The monitor input is set to HDMI 1.',
    user: 'Owen · Finance',
    icon: '🖥️',
    actions: [
      { label: 'Select HDMI 2 on the monitor', kind: 'fix', outcome: 'Negotiations successful. Picture restored.' },
      { label: 'Work on the laptop screen for now', kind: 'patch', outcome: 'Working, but I still need both screens.' },
      { label: 'Reconnect Wi-Fi', kind: 'wrong', outcome: 'The monitor remains unimpressed.' },
    ],
  },
  {
    id: 'numbers-as-text',
    category: 'SPREADSHEET',
    title: 'Creative accounting',
    quote: 'Three numbers, zero total. Bold financial strategy.',
    clue: 'The SUM range contains numeric text. Each cell is flagged Number stored as text.',
    user: 'Maya · Planning',
    icon: '📊',
    actions: [
      { label: 'Convert the affected cells to numbers', kind: 'fix', outcome: 'Arithmetic rejoins the team.' },
      { label: 'Check this total with a calculator', kind: 'patch', outcome: 'Total found. My spreadsheet is still broken.' },
      { label: 'Add two decimal places', kind: 'wrong', outcome: 'Two decimal places of nothing.' },
    ],
  },
  {
    id: 'accidental-browser-zoom',
    category: 'BROWSER',
    title: 'Website for giants',
    quote: 'I enlarged this by accident. Please put it back to normal.',
    clue: 'Browser zoom was accidentally changed to 200%. The user wants the previous 100% size.',
    user: 'Leo · Marketing',
    icon: '🔍',
    actions: [
      { label: 'Reset this browser to 100% zoom', kind: 'fix', outcome: 'Normal size. The button comes home.' },
      { label: 'Use the other browser at 100%', kind: 'patch', outcome: 'That works. Please fix my usual browser too.' },
      { label: 'Increase display brightness', kind: 'wrong', outcome: 'A brighter oversized problem.' },
    ],
  },
  {
    id: 'stale-saved-login',
    category: 'SIGN-IN',
    title: 'Password archaeology',
    quote: 'The desktop app is very committed to my previous password.',
    clue: 'Web sign-in works with the current password. The desktop app keeps submitting its old saved login.',
    user: 'Sam · Projects',
    icon: '🔑',
    actions: [
      { label: 'Refresh the desktop app sign-in', kind: 'fix', outcome: 'Old login retired. Desktop app connected.' },
      { label: 'Use the web app temporarily', kind: 'patch', outcome: 'Web works. I still need desktop sync.' },
      { label: 'Change the default browser', kind: 'wrong', outcome: 'New browser. Same stale desktop login.' },
    ],
  },
  {
    id: 'four-pages-per-sheet',
    category: 'PRINTING',
    title: 'Report for ants',
    quote: 'The printer thinks my audience is a colony of ants.',
    clue: 'The document looks normal on screen. Print preview shows 4 pages per sheet.',
    user: 'Jules · Training',
    icon: '🖨️',
    actions: [
      { label: 'Select one page per sheet', kind: 'fix', outcome: 'Human-readable again.' },
      { label: 'Read the PDF on screen for now', kind: 'patch', outcome: 'Readable. I still need full-size handouts.' },
      { label: 'Increase print darkness', kind: 'wrong', outcome: 'Darker text for the same ants.' },
    ],
  },
  {
    id: 'offscreen-window',
    category: 'DESKTOP',
    title: 'Window working remotely',
    quote: 'The app is open. Apparently somewhere else in the building.',
    clue: 'The app window is still positioned on a second display that was just disconnected.',
    user: 'Ada · People Ops',
    icon: '🪟',
    actions: [
      { label: 'Move the window onto the laptop display', kind: 'fix', outcome: 'App returns from remote work.' },
      { label: 'Reconnect the second display briefly', kind: 'patch', outcome: 'Found it. I need it working away from this desk.' },
      { label: 'Change the desktop wallpaper', kind: 'wrong', outcome: 'Lovely view. Missing window.' },
    ],
  },
  {
    id: 'outbox-offline',
    category: 'EMAIL',
    title: 'Outbox holding pattern',
    quote: 'My messages have formed a queue and appointed a spokesperson.',
    clue: 'The network is healthy. The mail client explicitly shows Work Offline; messages remain in its outbox.',
    user: 'Ben · Facilities',
    icon: '📨',
    actions: [
      { label: 'Turn off Work Offline and send the queue', kind: 'fix', outcome: 'Queue cleared. Spokesperson reassigned.' },
      { label: 'Use webmail for the next message', kind: 'patch', outcome: 'Webmail works. My outbox is still stuck.' },
      { label: 'Sort the outbox newest first', kind: 'wrong', outcome: 'A better-organized queue to nowhere.' },
    ],
  },
  {
    id: 'surprise-jazz',
    category: 'BROWSER',
    title: 'Mandatory surprise jazz',
    quote: 'The training video started itself. Please pause the jazz seminar.',
    clue: 'The training tab shows a speaker icon. Its video is playing and the user wants playback paused.',
    user: 'Erin · Support',
    icon: '🎷',
    actions: [
      { label: 'Pause the video in the training tab', kind: 'fix', outcome: 'The jazz committee adjourns.' },
      { label: 'Mute the tab temporarily', kind: 'patch', outcome: 'Quiet, but my lesson is still playing.' },
      { label: 'Lower the microphone level', kind: 'wrong', outcome: 'Jazz continues its solo.' },
    ],
  },
  {
    id: 'mouse-battery',
    category: 'HARDWARE',
    title: 'Mouse retirement notice',
    quote: 'My mouse has retired. I still need it for these layouts.',
    clue: 'The wireless mouse reports a depleted AA battery. The laptop trackpad works normally.',
    user: 'Kit · Creative',
    icon: '🖱️',
    actions: [
      { label: 'Replace the mouse battery', kind: 'fix', outcome: 'Retirement postponed. Cursor reporting for duty.' },
      { label: 'Use the laptop trackpad for now', kind: 'patch', outcome: 'Working, but I still need my mouse for layouts.' },
      { label: 'Increase double-click speed', kind: 'wrong', outcome: 'Still waiting for the first click.' },
    ],
  },
];
