import {test,expect} from '@playwright/test';
import {TICKETS} from '../js/rush-tickets.js';
import {BOSSES} from '../js/rush-bosses.js';
import {MANAGER_BOSS} from '../js/rush-manager-boss.js';
const KEY='sdh_dungeon_campaign_v1';
async function boot(page){await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.clock.install({time:new Date('2026-10-10T12:00:00Z')});await page.goto('/');await page.clock.pauseAt(new Date('2026-10-10T12:00:02Z'));}
async function tab(page,id){await page.locator(`[data-desk-tab="${id}"]`).click();await page.locator('[data-desk-filter="active"]').click();}
async function homeSave(page){await page.locator('#go-home-button').click();await page.locator('[data-evening="rest"]').click();await page.locator('[data-conversation="remember"]').click();await page.locator('#save-campaign').click();await expect(page.locator('#campaign-save-status')).toContainText('morning saved');return page.evaluate(key=>JSON.parse(localStorage.getItem(key)),KEY);}
async function quit(page){await page.locator('#pause-button').click();await page.locator('#quit-button').click();}
async function upgrades(page){await page.locator('#character-button').click();for(const id of ['systems-engineer','rollback-architect']){const b=page.locator(`[data-skill="${id}"]`);if(await b.isEnabled())await b.click();}for(const id of ['duct-tape-codex','ceremonial-blazer']){const b=page.locator(`[data-gear="${id}"]`);if(await b.isEnabled())await b.click();}const stat=page.locator('[data-level-stat="technical"]');if(await stat.isEnabled())await stat.click();await page.locator('#close-character-button').click();}
async function earn(page){
  await page.locator('[data-start-stat="technical"][data-stat-adjust="1"]').click();await page.locator('[data-start-stat="technical"][data-stat-adjust="1"]').click();await page.locator('#start-button').click();let diagnostics=0;
  for(let step=0;step<24&&await page.locator('#game').isVisible();step++){
    await upgrades(page);await tab(page,'projects');
    for(const id of ['portal-rollout','print-refresh']){const b=page.locator(`[data-project="${id}"][data-project-action="test"]`);if(await b.count()&&await b.isEnabled()){await b.click();await page.clock.fastForward(19000);await page.locator(`[data-project="${id}"][data-project-action="release"]`).click();await page.clock.fastForward(7000);}}
    if(await page.locator('#results').isVisible())break;
    let found=false;for(const id of ['req','inc']){await tab(page,id);const first=page.locator('#queue [data-ticket]').first();if(await first.count()){await first.click();found=true;break;}}
    if(!found){await page.locator('#skip-idle-button').click();for(const id of ['req','inc']){await tab(page,id);const first=page.locator('#queue [data-ticket]').first();if(await first.count()){await first.click();found=true;break;}}}
    expect(found).toBe(true);const title=await page.locator('#ticket-title').innerText();const source=[...TICKETS,...BOSSES.flatMap(b=>b.stages),...MANAGER_BOSS.stages].find(t=>t.title===title);expect(source).toBeTruthy();
    if(await page.locator('#acknowledge-button').isVisible())await page.locator('#acknowledge-button').click();
    const diagnostic=source.investigations.find(i=>i.kind==='diagnostic');if(diagnostics<2&&diagnostic){await page.locator('#diagnostics-button').click();await page.locator('[data-inquiry]').filter({hasText:diagnostic.label}).click();await page.clock.fastForward(5000);diagnostics++;}
    await page.locator('#fix-view-button').click();await page.locator('#actions button').filter({hasText:source.actions.find(a=>a.kind==='fix').label}).click();await page.clock.fastForward(3000);
  }
  await expect(page.locator('#results')).toBeVisible();return homeSave(page);
}
test('earned promotions and exact build survive reload; choosing a promoted technical path refreshes project timings',async({page})=>{
  await boot(page);const saved=await earn(page);expect(saved.carry.careerCarry.promotions).toBe(3);expect(saved.carry.dungeonCarry.skills).toEqual(['systems-engineer','rollback-architect']);expect(saved.carry.dungeonCarry.gear).toEqual(['duct-tape-codex','ceremonial-blazer']);expect(saved.carry.dungeonCarry.stats.technical).toBe(4);
  await page.reload();await page.locator('#resume-campaign').click();await page.locator('#character-button').click();await expect(page.locator('#career-panel')).toContainText('3/3 promotions');for(const id of saved.carry.dungeonCarry.skills)await expect(page.locator(`[data-skill="${id}"]`)).toHaveAttribute('aria-pressed','true');for(const id of saved.carry.dungeonCarry.gear)await expect(page.locator(`[data-gear="${id}"]`)).toHaveAttribute('aria-pressed','true');await expect(page.locator('[data-stat="technical"] [data-stat-value]').last()).toHaveText('4');await page.screenshot({path:'test-results/career-earned-resume.png',fullPage:true});await page.locator('#close-character-button').click();
  await tab(page,'projects');const button=page.locator('[data-project="portal-rollout"][data-project-action="test"]');const before=await button.innerText();await page.locator('#character-button').click();await page.locator('[data-career-path="technical"]').click();await page.locator('#close-character-button').click();await expect(button).not.toHaveText(before);await expect(button).toContainText('7.56s');await expect(page.locator('#projects')).toContainText('1.68 seconds versus release alone, or 9.24 including');
  // The same earned morning can select incident leadership. This seed has a portal defect.
  await page.reload();await page.locator('#resume-campaign').click();await tab(page,'projects');await page.locator('[data-project="portal-rollout"][data-project-action="unsafeRelease"]').click();await page.clock.fastForward(62000);await tab(page,'inc');await page.locator('#queue [data-ticket]').filter({hasText:'The portal has left the building'}).click();await page.locator('#acknowledge-button').click();
  const repair=page.locator('#actions button').filter({hasText:'Stop rollout, restore known-good version, and verify'}).locator('.action-duration');await expect(repair).toHaveText('1.872s');await page.locator('#character-button').click();await page.locator('[data-career-path="incident"]').click();await page.locator('#close-character-button').click();await expect(repair).toHaveText('1.498s');await expect(page.locator('#actions button').filter({hasText:'Silence the service alarm'}).locator('.action-duration')).toHaveText('1.498s');
  // Every mutation starts from this genuinely earned checkpoint. Loading must not normalize it.
  const mutations=[v=>delete v.carry.dungeonCarry,v=>v.carry.dungeonCarry.skills.push('unknown'),v=>v.carry.dungeonCarry.gear.push('unknown'),v=>v.life.memory='memory',v=>v.life.choices.inbox='inbox',v=>v.life.choices.evening='rest',v=>delete v.life.seed];
  mutations.push(v=>v.carry.dungeonCarry.previousDays=[null],v=>v.carry.dungeonCarry.previousDays=[{day:1,text:{}}],v=>v.carry.dungeonCarry.previousDays=Array.from({length:8},()=>({day:1,text:'Earlier day'})));
  for(const field of ['stats','skills','gear','gearFloors','checkpointsEarned','level','statPoints','skillPoints','gearChoices','initialStatBudget','xp','configured','day','floor','previousDays','journal','projectLog','bossReactions','xpKeys'])mutations.push(v=>delete v.carry.dungeonCarry[field]);
  for(const mutate of mutations){const bad=structuredClone(saved);mutate(bad);const raw=JSON.stringify(bad);await page.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key:KEY,raw});await page.reload();await expect(page.locator('#resume-campaign')).toBeHidden();expect(await page.evaluate(key=>localStorage.getItem(key),KEY)).toBe(raw);}
  // A damaged predecessor cannot be overwritten without the explicit replacement confirmation.
  const retained=await page.evaluate(key=>localStorage.getItem(key),KEY);await page.locator('#start-button').click();await quit(page);await page.locator('#go-home-button').click();await page.locator('[data-evening="rest"]').click();await page.locator('[data-conversation="remember"]').click();let prompted=false;page.once('dialog',async dialog=>{prompted=true;await dialog.dismiss();});await page.locator('#save-campaign').click();expect(prompted).toBe(true);expect(await page.evaluate(key=>localStorage.getItem(key),KEY)).toBe(retained);
});
test('unexpected character rendering failure leaves live work running instead of paused behind a closed dialog',async({page})=>{
  await boot(page);await page.locator('#start-button').click();const title=await page.locator('#ticket-title').innerText(),source=TICKETS.find(t=>t.title===title);await page.evaluate(()=>Object.defineProperty(document.getElementById('career-panel'),'innerHTML',{configurable:true,set(){throw new Error('Synthetic render failure');}}));await page.locator('#character-button').click();await expect(page.locator('#character-dialog')).not.toBeVisible();await expect(page.locator('#outcome')).toContainText('Work continues');await page.evaluate(()=>delete document.getElementById('career-panel').innerHTML);await page.locator('#acknowledge-button').click();await page.locator('#actions button').filter({hasText:source.actions.find(a=>a.kind==='fix').label}).click();await page.clock.fastForward(2500);await expect(page.locator('#time')).toHaveText('1 / 15');
});
test('workaround before return retains its title through clock-out, save and resume',async({page})=>{
  await boot(page);await page.locator('#start-button').click();const title=await page.locator('#ticket-title').innerText(),source=TICKETS.find(t=>t.title===title);await page.locator('#acknowledge-button').click();await page.locator('#actions button').filter({hasText:source.actions.find(a=>a.kind==='patch').label}).click();await page.clock.fastForward(1000);await quit(page);const saved=await homeSave(page);expect(saved.carry.careerCarry.consequences.filter(c=>c.text.includes(title))).toHaveLength(1);await page.reload();await page.locator('#resume-campaign').click();await page.locator('#character-button').click();await page.locator('#career-panel summary').click();await expect(page.locator('#career-panel')).toContainText(title);await expect(page.locator('#career-panel')).toContainText('restoration is not credited');
});
